### ISSUE TITLE
Unable to run the NavigationTests.kt for testing Navigation Component

### ISSUE THREAD

**Issue by shri-110011** [google-developer-training/android-basics-kotlin-words-app#293]
**URL of codelab**
https://developer.android.com/codelabs/android-basics-kotlin-test-navigation-components?continue=https%3A%2F%2Fdeveloper.android.com%2Fcourses%2Fpathways%2Fandroid-basics-kotlin-unit-3-pathway-2%23codelab-https%3A%2F%2Fdeveloper.android.com%2Fcodelabs%2Fandroid-basics-kotlin-test-navigation-components#5

**In which task and step of the codelab can this issue be found?**
While running the tests in android studio.

**Describe the problem**
Getting a runtime error while running the NavigationTests.kt file.
java.lang.AbstractMethodError: abstract method "androidx.navigation.NavDestination androidx.navigation.Navigator.navigate(androidx.navigation.NavDestination, android.os.Bundle, androidx.navigation.NavOptions, androidx.navigation.Navigator$Extras)"
at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.java:71)
at androidx.navigation.NavGraphNavigator.navigate(NavGraphNavigator.java:28)
at androidx.navigation.NavController.navigate(NavController.java:1049)
at androidx.navigation.NavController.onGraphCreated(NavController.java:633)
at androidx.navigation.NavController.setGraph(NavController.java:586)
at androidx.navigation.NavController.setGraph(NavController.java:551)
at androidx.navigation.NavController.setGraph(NavController.java:533)
at com.example.wordsapp.NavigationTests.navigate_to_words_nav_component$lambda-0(NavigationTests.kt:33)
at com.example.wordsapp.NavigationTests.$r8$lambda$jLCcGvWkB9P5E7T4FbIqpa_QZ-A(Unknown Source:0)
at com.example.wordsapp.NavigationTests$$ExternalSyntheticLambda0.perform(Unknown Source:4)
at androidx.fragment.app.testing.FragmentScenario.onFragment$lambda-6(FragmentScenario.kt:397)
at androidx.fragment.app.testing.FragmentScenario.$r8$lambda$Iy3YR7P8PCct5YCPTCTE7shTmro(Unknown Source:0)
at androidx.fragment.app.testing.FragmentScenario$$ExternalSyntheticLambda0.perform(Unknown Source:6)
at androidx.test.core.app.ActivityScenario.lambda$onActivity$2$ActivityScenario(ActivityScenario.java:660)
at androidx.test.core.app.ActivityScenario$$Lambda$4.run(ActivityScenario.java:652)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at android.app.Instrumentation$SyncRunnable.run(Instrumentation.java:2207)
at android.os.Handler.handleCallback(Handler.java:883)
at android.os.Handler.dispatchMessage(Handler.java:100)
at android.os.Looper.loop(Looper.java:214)
at android.app.ActivityThread.main(ActivityThread.java:7356)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Steps to reproduce?**
1. Go to...
2. Click on...
3. See error...

**Versions**
_Android Studio version:_ 
Android Studio Chipmunk | 2021.2.1

_API version of the emulator:_ 
Pixel 3a API 29

**Additional information**
_Include screenshots if they would be useful in clarifying the problem._

**Comment by Sonofasleep** [comment]
I have same error, but as seen somewhere, you can downgrade in gradle(:app) test navigation to 2.3.5 and it works

Here what working impementation looks like:
androidTestImplementation 'androidx.navigation:navigation-testing:2.3.5'

P.s. don't forget to sync gradle before launching test.

**Comment by h-takeyeah** [comment]
I had same error.

In my case, the problem was that `navigation-testing` and `navigation-fragment` had different versions. Why don't you try checking they are same version in build.gradle(:app)?

**Comment by Sonofasleep** [comment]
Yes, that was the case. Thank you!

**Comment by schordas** [comment]
The necessary dependencies and versions have now been updated in the codelab and all of the branches.
